### PR TITLE
Add search engines

### PR DESCRIPTION
**Pull request by vasconcelloslf**
Hey @bruno- 

I'm creating another PR as you asked. Can you check to see if this one is alright?

### CODE REVIEW

**Comment by bruno-** [comment]
Hey, this is merged. I've done it via the command line because I wanted to do some whitespace updates 0e22a2186 (using tabs instead of spaces for indentation).

I'll add you as the repo collaborator so you can make updates to the README so ppl know we have this new feature.

**Comment by bruno-** [comment]
All right @vasconcelloslf, I just invited you to the team!

Let's just agree on one thing: we'll do all the changes via pull request so each of us can look at the changes being made, point improvements etc.<br/>
Also if we're about to make a bigger change, we're better off discussing it via an issue first.

Apart from that, welcome to the team! :tada: :tada: (given that you accept the invite lol)

**Comment by vasconcelloslf** [comment]
Hey, sorry for the late reply. Thanks for the invitation, off course I will accept it!
All changes via PR, got it!
=)

**Comment by hoschi** [comment]
Can you put an example in `README.md` ? I didn't get it to work to :(

**Pull request closed without merging**
